spring:
  application:
    name: 4nabiji-ecommerce

  datasource:
    password: 953012
    url: jdbc:postgresql://localhost:5432/nabiji_db
    username: postgres

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: 4NabijiStoreApplication24hoursinmilliseconds
  expiration: 86400000

logging:
  level:
    com.nabiji.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.description.sql.BasicBinder: TRACE

server:
  port: 8080

  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      try-it-out-enabled: true
      operations-sorter: alpha
      tags-sorter: alpha
      filter: false
      show-actuator: true